### ISSUE TITLE
Testing locally should be easier

### ISSUE THREAD

**Issue by stof** [craue/CraueConfigBundle#24]
Several things could be done to make testing easier:

- using sqlite rather than mysql, as it avoids the need to setup a MySQL access (which cannot be configured)
- document the needed setup
- ensure that the git repo stays in a clean state after running the testsuite (currently, it is not as the cache lives inside the package and is not ignored)

**Comment by craue** [comment]
Regarding your 3rd point: Afaik, the only way to set a different cache path is in the `AppKernel`, so I'm using an uncommitted [`LocalAppKernel`](https://github.com/craue/CraueConfigBundle/blob/1.3.1/Tests/IntegrationTestCase.php#L44) which extends the default one and defines a custom cache and log dir.

**Comment by craue** [comment]
1. #26 adds support to run tests with SQLite by default.
1. I guess with that PR being merged, there's no further setup needed. Or did you encounter any other issues when trying to run the tests for the first time?
1. The cache folder is actually [ignored](https://github.com/craue/CraueConfigBundle/blob/1.3.1/Tests/.gitignore#L1).

**Comment by stof** [comment]
@craue why not using the AppKernel of the testsuite but making use a folder in sys_get_temp_dir for its cache and logs ? this is what Symfony does in its functional tests

regarding the cache folder, my bad. I got confused by a weird behavior of the PhpStorm gitignore plugin.

**Comment by craue** [comment]
I want those folders (cache and log) to be created in a custom location, which is not the system temp dir and couldn't find a different way of achieving that.

**Comment by stof** [comment]
Well, you can make an implementation getting the settings from ``$_SERVER`` variables by default, and falling back to the system temp dir when not set. This way, you would just need to create a phpunit.xml file locally which would set the needed variables to overwrite it.

**Comment by craue** [comment]
Good idea. I've added a commit to #26 for that, but using `$_ENV` instead as it seems to fit better.
