### ISSUE TITLE
Travis should run some builds without changing the requirements

### ISSUE THREAD

**Issue by stof** [craue/CraueConfigBundle#27]
This would ensure that the requirements defined in the composer.json are fine.

**Comment by craue** [comment]
When you say **some**, what exactly do you have in mind? I could just add one more job if this is sufficient.

**Comment by stof** [comment]
Well, I mean at least 1 job. But what I do in general is letting the main jobs running different PHP version cover this, and adding specific requirements only in the extra jobs included in the matrix.
