### ISSUE TITLE
preSave / preUpdate events

### ISSUE THREAD

**Issue by ikvasnica** [craue/CraueConfigBundle#31]
It would be great if the bundle allows us to subscribe to some events - especially right before saving or updating a setting.

I need to validate some of the settings (f.e. to be only numeric). Sure, I can write my own controller and form, but this would be an easier way.

**Comment by craue** [comment]
But you wouldn't be able to properly render form errors by using such an event, right?

**Comment by ikvasnica** [comment]
@craue That's true. Anyway, the need for differentiating string / numeric / other types of settings and validating them is still here, because now only strings are supported.

Also, an option to hook into the mentioned events might be useful, even though not for this particular issue.

**Comment by craue** [comment]
The bundle probably won't support different data types (see #5, #29), so you'll have to save the values as strings and handle them as needed.

Could you be more precise about the additional features you'd like to use?
