### ISSUE TITLE
How to get settings into a Symfony Command?

### ISSUE THREAD

**Issue by KhanMaytok** [craue/CraueConfigBundle#48]
Hi. I'm trying to get the settings work into a symfony command that I created

The command extends from `ContainerAwareCommand`.

I tried with

`$this->getContainer()->getParameter('craue_config')->get('enterprise_ruc')`

But doesn't works

**Comment by craue** [comment]
Try `$this->getContainer()->get('craue_config')->get('enterprise_ruc')` instead.

**Comment by KhanMaytok** [comment]
Works! many thanks for the response
