### ISSUE TITLE
Cached value not getting flushed after updated from the web.

### ISSUE THREAD

**Issue by elvismdev** [craue/CraueConfigBundle#54]
I'm enabling caching using `DoctrineCacheBundle` and a custom entity where settings are stored.

This entity is also being managed from a basic web backend with easy admin bundle.

When a config value is changed from the web interface, it still returns the old value when called from twig or controllers since it's kept getting cached. I have to manually flush it from the command line. 

Why is this value not getting removed from the cache if updated within the app?  Might I be missing something else in my setup?

**Comment by craue** [comment]
Whenever the value of a setting is updated (either by the built-in controller action or the `Config` util class), its cached version is updated as well.

Can you try to narrow down the issue? Without seeing some code, I cannot tell what could be wrong there.

**Comment by craue** [comment]
Well, it's been over 3 years now but I prepared something in #62. 😂
Are you still interested in checking if it solves the issue, @elvismdev?
