### ISSUE TITLE
There is no extension able to load the configuration for "craue_config_settings"

### ISSUE THREAD

**Issue by linnit** [craue/CraueConfigBundle#56]
Following the steps in the README.

Installed the package, loading the migration, updated routing.yaml, but I get the error:

`There is no extension able to load the configuration for "craue_config_settings"`

**Comment by linnit** [comment]
Resolved by creating config/routes/craue_config.yaml, with the contents:
`
_craue_config:
  resource: "@CraueConfigBundle/Resources/config/routing/settings.xml"
  prefix: /admin/settings
`

**Comment by craue** [comment]
Importing or adding the route is indeed needed if you want to use the built-in form, but not defining a route shouldn't cause the error you mentioned initially.
